version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: echopub_mongodb_dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: echopub
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: echopub_backend_dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/echopub?authSource=admin
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    depends_on:
      - mongodb

volumes:
  mongodb_data:
    driver: local
